# Permalinks
permalink:           pretty

# Setup
title:               Morgan C Evans
tagline:             
url:                 https://mce32.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
sass_dir:          _sass
style:            :compressed

# About/contact
author:
name:              Morgan C Evans
url:               https://twitter.com/mcevns
email:             morganev@cs.cmu.edu

# Custom vars
version:             2.0.1
github:
  repo:             
google_analytics:    UA-135252832-1
twitter:             mcevns
github:              
linkedin:            mcevns

# Gems
plugins:
# - jekyll-paginate
# - jekyll-gist


